- name: Compare Storage Account
  hosts: localhost
  gather_facts: false

  vars:
    storageaccountnames: []

  collections:
    - azure.azcollection

  tasks: 

    - name: Load stored resource groups
      include_vars:
        file: vars/storage_account.yml
        name: master_storage

    - name: Get facts for all storage accounts
      azure_rm_storageaccount_info:
        resource_group: Demo
      register: storageaccount
      
    - name: Gather storage account names
      set_fact:
        storageaccountnames: "{{ storageaccountnames }} + [ '{{ item.name }}' ]"
      loop: "{{ storageaccount.storageaccounts }}"
      when: storageaccount != []

    - name: Print difference storage
      debug:
        msg: "{{ storageaccountnames | difference(master_storage.storage_account) }}"

    - name: Set facts to remove the extra storage accounts
      set_fact:
        storage_account_name: "{{ storageaccountnames | difference(master_storage.storage_account) }}"

    - name: Remove extra storage
      include_tasks: remove_storageaccount_task.yml
      when: storage_account_name != []
